update semaphore (#14)
* test

* remove docker commands

* change test running

* change setup

* change setup(1)

* change setup(2)

* change setup(3)

* change setup(4)

* change setup(5)

* change setup(6)

* change setup(7)

* change setup(8)

* change setup(9)

* change setup(10)

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,16 +1,18 @@
-#!/usr/bin/env sh
+#!/usr/bin/env ruby
+require 'fileutils'
 
-set -e
+# path to your application root.
+APP_ROOT = File.expand_path('..', __dir__)
 
-if [ ! -f .env ]; then
-  cp .env.example .env
-fi
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-if [ ! -f docker-compose.override.yml ]; then
-  cp docker-compose.linux.yml docker-compose.override.yml
-fi
+FileUtils.chdir APP_ROOT do
+  FileUtils.cp '.env.example', '.env' unless File.exist?('.env')
 
-docker-compose up --detach
-docker-compose exec app bin/rails db:create db:schema:load
-docker-compose exec app bin/rails db:seed
-docker-compose stop
+  system! 'bundle install'
+  system! 'bin/rails db:create db:schema:load'
+  system! 'bin/rails db:seed'
+  system! 'bin/rails restart'
+end
